In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("IMDB_10000.csv")
df

,title,year,certificate,runtime,genre,desc,rating,votes
0,Freddy,2022,UA 16+,124 min,"Drama, Mystery, Thriller",The lines between love and obsession blur in t...,7.9,"16,441"
1,An Action Hero,2022,U,130 min,Action,Youth Icon. Superstar. Action Hero. At the age...,8.1,"15,690"
2,Kantara,2022,UA,148 min,"Action, Adventure, Drama",It involves culture of Kambala and Bhootha Kol...,8.7,"78,358"
3,Khakee: The Bihar Chapter,2022–,UA 13+,45 min,"Action, Crime, Drama",As a righteous cop pursues a merciless crimina...,8.3,"4,464"
4,Drishyam 2,2022,UA,140 min,"Crime, Drama, Mystery",A gripping tale of an investigation and a fami...,8.6,"18,743"
...,...,...,...,...,...,...,...,...
9995,Kisan Aur Bhagwan,1974,NaN,142 min,"Action, Comedy, Drama",NaN,NaN,NaN
9996,Aadmi Sadak Ka,1977,NaN,138 min,"Drama, Family",NaN,NaN,NaN
9997,Nadodi Mannan,1958,NaN,220 min,"Action, Adventure, Comedy",NaN,NaN,NaN
9998,Njan Marykutty,2018,U,126 min,Drama,NaN,NaN,NaN


In [3]:
df = df.dropna()
df.shape

(5440, 8)

In [4]:
df

,title,year,certificate,runtime,genre,desc,rating,votes
0,Freddy,2022,UA 16+,124 min,"Drama, Mystery, Thriller",The lines between love and obsession blur in t...,7.9,"16,441"
1,An Action Hero,2022,U,130 min,Action,Youth Icon. Superstar. Action Hero. At the age...,8.1,"15,690"
2,Kantara,2022,UA,148 min,"Action, Adventure, Drama",It involves culture of Kambala and Bhootha Kol...,8.7,"78,358"
3,Khakee: The Bihar Chapter,2022–,UA 13+,45 min,"Action, Crime, Drama",As a righteous cop pursues a merciless crimina...,8.3,"4,464"
4,Drishyam 2,2022,UA,140 min,"Crime, Drama, Mystery",A gripping tale of an investigation and a fami...,8.6,"18,743"
...,...,...,...,...,...,...,...,...
8953,Pyaar Kii Ye Ek Kahaani,2010–2021,PG,24 min,"Fantasy, Romance",The story of a young village girl who abandons...,8.4,17
8954,Hero Gayab Mode On,2020–2021,UA 13+,23 min,"Action, Adventure, Fantasy","Ghasitaram, under pressure from his wife, deci...",6.6,23
8955,Aakashavaani,2021,UA 16+,124 min,Drama,The Nath family consists of Retired Commission...,5.5,39
8956,Aladdin - Naam Toh Suna Hoga,2018–2021,U,22 min,Fantasy,A wanderer/revolutionary is a dead ringer for ...,8.1,110


In [5]:
features = df.columns.to_list()
print(features)

['title', 'year', 'certificate', 'runtime', 'genre', 'desc', 'rating', 'votes']


In [14]:
titleFeature = df['title']
descFeature = df['desc']
genreFeature = df['genre'].str.replace(","," ")
# genreFeature
descFeature

0       The lines between love and obsession blur in t...
1       Youth Icon. Superstar. Action Hero. At the age...
2       It involves culture of Kambala and Bhootha Kol...
3       As a righteous cop pursues a merciless crimina...
4       A gripping tale of an investigation and a fami...
                              ...                        
8953    The story of a young village girl who abandons...
8954    Ghasitaram, under pressure from his wife, deci...
8955    The Nath family consists of Retired Commission...
8956    A wanderer/revolutionary is a dead ringer for ...
8957    A transsexual man's attempt to realize his tru...
Name: desc, Length: 5440, dtype: object

In [7]:
uniqueFeatures = ['year','certificate','genre']
genre = []
for i in uniqueFeatures:
    if i=='genre':
        genre = df[i].unique()
    print(i)
    print(df[i].unique())
    print("\n")


year
['2022' '2022–' 'I 2022' '2016' '2019' '2018–' '2018' '2011' '2008' '2009'
 '2015' 'III 2022' '2017' '2020' '2020–' '2021' '2012' '2019–2022' '2019–'
 '2021–' '2004' 'I 2006' 'I 2017' '1982' '2014' '2007' '2011–2018'
 '2018–2019' '2019–2021' '2015–2022' '2023' 'I 2010' 'V 2022' 'II 2022'
 'I 2016' 'I 2021' '2016–' '2006' 'I 2018' '2015–' '2001' '2013' '2003'
 '1998' '2010' '2006–' '1955' 'I 2002' '1995' 'III 2018' 'I 2020' 'I 2013'
 '2017–' 'II 2020' '1959' '2020–2022' '2014–' '2000–2008' 'III 2016'
 '1991' '2016–2019' '2002' '2000' '2016–2017' 'II 2018' 'I 2020–'
 '2013–2016' '2013–2014' '1993' '1975' 'XVII 2016' '2005' '1994' '1957'
 'II 2019' '2004–' '2009–' 'I 2014' '1988–1990' 'I 2019' '2011–2014'
 '1997' '1987–1988' '2016–2021' '2003–2007' 'I 2011' '2008–' 'III 2021'
 'VI 2020' 'I 2015' '2011–2016' '1999' '2019–2020' '1956' '2004–2017'
 '2013–2015' '1988' '1987' '2014–2015' 'III 2019' '2011–2013' '2009–2011'
 '2003–2004' '1963' '2013–2019' '2005–2007' '1998–2018' '2008 Video

#### Genre based Only

In [8]:
# genre = genre.tolist()
# print(genre)
uniqueGenre = set()
for i in genre:
    Glist = i.split(",")
    for j in Glist:
        if j[0]==" " or j[len(j)-1]==" ":
            removeSpace = j.split(" ")
            for u in removeSpace:
                if u!=" ":
                    uniqueGenre.add(u)
        else:
            uniqueGenre.add(j)
print(uniqueGenre)
print(len(uniqueGenre))


{'', 'Horror', 'Game-Show', 'Crime', 'Animation', 'Comedy', 'History', 'Talk-Show', 'Musical', 'Romance', 'Short', 'Sci-Fi', 'Drama', 'Western', 'Fantasy', 'News', 'Biography', 'Documentary', 'Sport', 'Music', 'Mystery', 'Adventure', 'Action', 'Reality-TV', 'War', 'Family', 'Thriller'}
27


In [9]:
# k = " Drama            "
# k= "Family            "
# if j[0]==" " or j[len(j)-1]==" ":
#         removeSpace = k.split(" ")
#         for u in removeSpace:
#             if u!=" ":
#                   uniqueGenre.add(j)
#         print(removeSpace)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

vec = vectorizer.fit_transform(genreFeature)
print(vectorizer.get_feature_names_out())

search = "drama thriller"
srchVec = vectorizer.transform([search])

# print(vec.toarray())

['action' 'adventure' 'animation' 'biography' 'comedy' 'crime'
 'documentary' 'drama' 'family' 'fantasy' 'fi' 'game' 'history' 'horror'
 'music' 'musical' 'mystery' 'news' 'reality' 'romance' 'sci' 'short'
 'show' 'sport' 'talk' 'thriller' 'tv' 'war' 'western']
['action' 'adventure' 'animation' 'biography' 'comedy' 'crime'
 'documentary' 'drama' 'family' 'fantasy' 'fi' 'game' 'history' 'horror'
 'music' 'musical' 'mystery' 'news' 'reality' 'romance' 'sci' 'short'
 'show' 'sport' 'talk' 'thriller' 'tv' 'war' 'western']


In [11]:
from sklearn.metrics.pairwise import cosine_similarity

similar = cosine_similarity(srchVec,vec).flatten()
print(similar)

topK = 5
topIndex = np.argsort(similar)[::-1][:topK]
print(topIndex)


[0.81649658 0.         0.40824829 ... 0.70710678 0.         0.        ]
[ 419   22 1433 3098 3112]


In [12]:
for i in topIndex:
    print(df['title'].iloc[i])
    print("Cosine Value: ", similar[i])
    print("\n")


Trapped
Cosine Value:  0.9999999999999998


Blurr
Cosine Value:  0.9999999999999998


Malayankunju
Cosine Value:  0.9999999999999998


Meppadiyan
Cosine Value:  0.9999999999999998


Maalgudi Days
Cosine Value:  0.9999999999999998




#### Desc based Only

In [15]:
descFeature

0       The lines between love and obsession blur in t...
1       Youth Icon. Superstar. Action Hero. At the age...
2       It involves culture of Kambala and Bhootha Kol...
3       As a righteous cop pursues a merciless crimina...
4       A gripping tale of an investigation and a fami...
                              ...                        
8953    The story of a young village girl who abandons...
8954    Ghasitaram, under pressure from his wife, deci...
8955    The Nath family consists of Retired Commission...
8956    A wanderer/revolutionary is a dead ringer for ...
8957    A transsexual man's attempt to realize his tru...
Name: desc, Length: 5440, dtype: object

In [29]:
vectorizer = CountVectorizer()

decvec = vectorizer.fit_transform(descFeature)
print(vectorizer.get_feature_names_out())

# searchDec = "Action based new cool fiction story"
searchDec = "horror"
srchDecVec = vectorizer.transform([searchDec])

# print(vec.toarray())

['000' '10' '100' ... 'zuhu' 'zumba' 'zwigato']


In [30]:
from sklearn.metrics.pairwise import cosine_similarity

similarDec = cosine_similarity(srchDecVec,decvec).flatten()
print(similarDec)

topK = 5
topIndexDec = np.argsort(similarDec)[::-1][:topK]
print(topIndexDec)


[0. 0. 0. ... 0. 0. 0.]
[1820 3169 3064  940  943]


In [ ]:
for i in topIndexDec:
    print(df['title'].iloc[i])
    print("Cosine Value: ", similarDec[i])
    print(df['desc'].iloc[i])
    print("\n")
